### ISSUE TITLE
Allow implementors to provide their own `validate()` function

### ISSUE THREAD

**Issue by mattbasta** [alanclarke/time-input#18]
The `validate()` function that's provided only allows for a very specific timestamp format, specifically timestamps with leading zeroes. It would be great if a `validate={}` prop could be passed that would allow the implementor to provide their own validator.

**Comment by alanclarke** [comment]
In general I think validation should happen at the form level, not at the level of individual inputs, but am open to hearing legitimate use cases for this

**Comment by alanclarke** [comment]
formatting requirement covered here: https://github.com/alanclarke/time-input/issues/21
