### ISSUE TITLE
Deprecations warnings (react@15.5.0)

### ISSUE THREAD

**Issue by craigdallimore** [alanclarke/time-input#23]
Hello!

Recently [React 15.5](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) was released, and with it come some deprecations for `React.createClass` and `React.propTypes`. At present it looks like `time-input` is still using the deprecated API - causing warnings to be emitted to the JS console and when running tests. Would it be possible to update to the new API? Happy to provide a PR.

**Comment by radumardale** [comment]
I've submitted a [PR](https://github.com/alanclarke/time-input/pull/24) for this.

**Comment by alanclarke** [comment]
thanks @craigdallimore and @radumardale, merged and released

**Comment by craigdallimore** [comment]
Thank you both 👍
